/*
 * generated by Xtext 2.20.0
 */
package dk.klevang.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractMathInterpreterValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(dk.klevang.mathInterpreter.MathInterpreterPackage.eINSTANCE);
		return result;
	}
}
