/*
 * generated by Xtext 2.20.0
 */
package dk.klevang.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMathInterpreterScopeProvider extends DelegatingScopeProvider {
}
