/*
 * generated by Xtext 2.20.0
 */
package dk.klevang.ui;

import com.google.inject.Injector;
import dk.klevang.mathInterpreter.ui.internal.MathInterpreterActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MathInterpreterExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(MathInterpreterActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		MathInterpreterActivator activator = MathInterpreterActivator.getInstance();
		return activator != null ? activator.getInjector(MathInterpreterActivator.DK_KLEVANG_MATHINTERPRETER) : null;
	}

}
