/**
 * generated by Xtext 2.20.0
 */
package dk.klevang.ui;

import dk.klevang.ui.AbstractMathInterpreterUiModule;
import dk.klevang.ui.hover.MyHoverClass;
import dk.klevang.ui.hover.MyHoverContent;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.documentation.IEObjectDocumentationProvider;
import org.eclipse.xtext.ui.editor.hover.IEObjectHoverProvider;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@SuppressWarnings("all")
public class MathInterpreterUiModule extends AbstractMathInterpreterUiModule {
  public MathInterpreterUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
  
  public Class<? extends IEObjectHoverProvider> bindIEObjectHoverProvider() {
    return MyHoverClass.class;
  }
  
  public Class<? extends IEObjectDocumentationProvider> bindIEObjectDocumentationProvider() {
    return MyHoverContent.class;
  }
}
