/*
 * generated by Xtext 2.20.0
 */
package dk.klevang.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import dk.klevang.MathInterpreterRuntimeModule;
import dk.klevang.MathInterpreterStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MathInterpreterIdeSetup extends MathInterpreterStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MathInterpreterRuntimeModule(), new MathInterpreterIdeModule()));
	}
	
}
