/**
 * generated by Xtext 2.20.0
 */
package dk.klevang.mathInterpreter.impl;

import dk.klevang.mathInterpreter.Div;
import dk.klevang.mathInterpreter.MathInterpreterPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Div</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DivImpl extends ExpImpl implements Div
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DivImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MathInterpreterPackage.Literals.DIV;
  }

} //DivImpl
