/**
 * generated by Xtext 2.20.0
 */
package dk.klevang.mathInterpreter;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Math Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.klevang.mathInterpreter.MathExp#getMathVar <em>Math Var</em>}</li>
 *   <li>{@link dk.klevang.mathInterpreter.MathExp#getExp <em>Exp</em>}</li>
 *   <li>{@link dk.klevang.mathInterpreter.MathExp#getLeft <em>Left</em>}</li>
 *   <li>{@link dk.klevang.mathInterpreter.MathExp#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see dk.klevang.mathInterpreter.MathInterpreterPackage#getMathExp()
 * @model
 * @generated
 */
public interface MathExp extends EObject
{
  /**
   * Returns the value of the '<em><b>Math Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Math Var</em>' containment reference.
   * @see #setMathVar(Exp)
   * @see dk.klevang.mathInterpreter.MathInterpreterPackage#getMathExp_MathVar()
   * @model containment="true"
   * @generated
   */
  Exp getMathVar();

  /**
   * Sets the value of the '{@link dk.klevang.mathInterpreter.MathExp#getMathVar <em>Math Var</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Math Var</em>' containment reference.
   * @see #getMathVar()
   * @generated
   */
  void setMathVar(Exp value);

  /**
   * Returns the value of the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp</em>' containment reference.
   * @see #setExp(Exp)
   * @see dk.klevang.mathInterpreter.MathInterpreterPackage#getMathExp_Exp()
   * @model containment="true"
   * @generated
   */
  Exp getExp();

  /**
   * Sets the value of the '{@link dk.klevang.mathInterpreter.MathExp#getExp <em>Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp</em>' containment reference.
   * @see #getExp()
   * @generated
   */
  void setExp(Exp value);

  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(MathExp)
   * @see dk.klevang.mathInterpreter.MathInterpreterPackage#getMathExp_Left()
   * @model containment="true"
   * @generated
   */
  MathExp getLeft();

  /**
   * Sets the value of the '{@link dk.klevang.mathInterpreter.MathExp#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(MathExp value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(Exp)
   * @see dk.klevang.mathInterpreter.MathInterpreterPackage#getMathExp_Right()
   * @model containment="true"
   * @generated
   */
  Exp getRight();

  /**
   * Sets the value of the '{@link dk.klevang.mathInterpreter.MathExp#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(Exp value);

} // MathExp
