/**
 * generated by Xtext 2.20.0
 */
package dk.klevang.mathInterpreter;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Minus</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dk.klevang.mathInterpreter.MathInterpreterPackage#getMinus()
 * @model
 * @generated
 */
public interface Minus extends Exp
{
} // Minus
