/**
 * generated by Xtext 2.20.0
 */
package dk.klevang.mathInterpreter;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mult</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dk.klevang.mathInterpreter.MathInterpreterPackage#getMult()
 * @model
 * @generated
 */
public interface Mult extends Exp
{
} // Mult
