/**
 * generated by Xtext 2.20.0
 */
package dk.klevang.mathInterpreter;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mult</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.klevang.mathInterpreter.Mult#getOp <em>Op</em>}</li>
 * </ul>
 *
 * @see dk.klevang.mathInterpreter.MathInterpreterPackage#getMult()
 * @model
 * @generated
 */
public interface Mult extends Exp
{
  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see #setOp(String)
   * @see dk.klevang.mathInterpreter.MathInterpreterPackage#getMult_Op()
   * @model
   * @generated
   */
  String getOp();

  /**
   * Sets the value of the '{@link dk.klevang.mathInterpreter.Mult#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see #getOp()
   * @generated
   */
  void setOp(String value);

} // Mult
