/*
 * generated by Xtext 2.20.0
 */
package dk.klevang;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MathInterpreterStandaloneSetup extends MathInterpreterStandaloneSetupGenerated {

	public static void doSetup() {
		new MathInterpreterStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
