/*
 * generated by Xtext 2.20.0
 */
package dk.klevang.ui.tests;

import com.google.inject.Injector;
import dk.klevang.mathInterpreter.ui.internal.MathInterpreterActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MathInterpreterUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MathInterpreterActivator.getInstance().getInjector("dk.klevang.MathInterpreter");
	}

}
